### ISSUE TITLE
Gain not working

### ISSUE THREAD

**Issue by brydavis** [faiface/beep#29]
Audio sounds the same...

    package main

    import (
        "log"
        "os"
        "time"

        "github.com/faiface/beep"
        "github.com/faiface/beep/effects"
        "github.com/faiface/beep/mp3"
        "github.com/faiface/beep/speaker"
    )

    func main() {
        // Open first sample File
        fileName := "somesong.mp3" // os.Args[1]

        f, err := os.Open(fileName)

        // Check for errors when opening the file
        if err != nil {
            log.Fatal(err)
        }

        // Decode the .mp3 File, if you have a .wav file, use wav.Decode(f)
        s, _, _ := mp3.Decode(f)

        start := int(float64(s.Len()) * (2 / 5)) //  start on minute 2 of 5 minute song
        s.Seek(start)

        speed := 1.0                                 // 0.75
        sampleRate := beep.SampleRate(44100 * speed) // integer

        // Init the Speaker with the SampleRate of the format and a buffer size of 1/10s
        speaker.Init(sampleRate, sampleRate.N(time.Second/10))

        // Channel, which will signal the end of the playback.
        playing := make(chan struct{})

        // Now we Play our Streamer on the Speaker
        speaker.Play(
            beep.Seq(
                effects.Gain{
                    Streamer: s,
                    Gain:     1.9,
                }.Streamer,
                // []beep.Streamer{v1}...,
                beep.Callback(func() {
                    // Callback after the stream Ends
                    close(playing)
                }),
            ),
        )

        <-playing
    }

**Comment by faiface** [comment]
It's because you're passing `effects.Gain{...}.Streamer` to the speaker. The important part is the `.Streamer` part. You're not passing the gain, you're just passing your original `s`. Instead, you need to pass the actual gain effect, so you need to change `effects.Gain{...}.Streamer` to `&effects.Gain{...}` (dropped `.Streamer`, added `&`, because `&effects.Gain`, not `effects.Gain` implements `beep.Streamer` interface) and it'll work.
