### ISSUE TITLE
Re-playing a stream using speaker?

### ISSUE THREAD

**Issue by Lallassu** [faiface/beep#45]
I'm trying to integrate the beep library in a game, but I have a hard time to find information how to play a sound over and over again. I want to load resources during startup and currently I'm saving the decoded streams. Then I just want to call speaker.Play(stream) upon an event. But that only plays the sound once. Calling it again does nothing.

Any example how to replay and re-use streams?

This is my test-code for playing mp3/wav:
```

  type sound struct {
	sounds map[string]beep.StreamSeekCloser
   }

    func (s *sound) create() {
	s.sounds = make(map[string]beep.StreamSeekCloser)

	for _, file := range gSoundFiles {
		f, _ := os.Open(fmt.Sprintf("assets/sounds/%v", file))
		if strings.Contains(file, "mp3") {
			name := strings.TrimSuffix(file, ".mp3")
			stream, format, err := mp3.Decode(f)
			if err != nil {
				panic("Failed to load sound")
			}
			s.sounds[name] = stream
			speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))
		} else if strings.Contains(file, "wav") {
			name := strings.TrimSuffix(file, ".wav")
			stream, format, err := wav.Decode(f)
			if err != nil {
				panic("Failed to load sound")
			}
			s.sounds[name] = stream
			speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))
		}
	}
    }

    func (s *sound) play(name string) {
     	speaker.Play(s.sounds[name])
    }

```

**Comment by faiface** [comment]
Hi, Streamers generally get drained after they're played. Of course, I have implemented things to achieve what you want :).

The first thing that you can do is to seek the streamer back to the beginning. That's, however, not optimal, because this way you will be loading the file over and over from the disk.

The second, correct, way is to make a `beep.Buffer`. A buffer is just a storage location for sound. You can append data to it just like you append data to a slice. So, you call `buffer.Append(stremer)`. The streamer gets drained just like when you play it, but the data gets stored in the buffer.

Now, when you have data in the buffer, you can create unlimited number of streamers without any cost. Just call `buffer.Streamer(from, to)` to generate a streamer, which you can then play. Of course, after playing the streamer gets drained, but it's no problem creating another one whenever needed.

**Comment by Lallassu** [comment]
That worked great! Thanks @faiface !
