### ISSUE TITLE
Control the sound

### ISSUE THREAD

**Issue by mbn18** [faiface/beep#8]
I setup a mixer playing two mp3 files at the same time. I wish to raise/lower the volume of one of them but cant seems to accomplish that.

Another problem is that I dont understand what values to assign to `samples [][2]float64`

The code bellow mix two streams at same time and also include my naive not working volume manipulation code. What am I doing wrong?

	func main() {
		println("Hi")
		f1, _ := os.Open("data/03_Summertime.mp3")
		s1, format, _ := mp3.Decode(f1)
		f2, _ := os.Open("data/Pink Floyd.mp3")
		s2, format, _ := mp3.Decode(f2)

		v1 := effects.Volume{
			Streamer: s2,
			Base:     2,
			Volume:   -2000,
		}
		samples := [][2]float64{{-50.0, -50.0}, {-50.0, -50.0}}
		v1.Stream(samples)

		mixer := new(beep.Mixer)
		mixer.Play(s1)
		mixer.Play(s2)
		println(mixer.Len())

		speaker.Init(format.SampleRate, format.SampleRate.N(time.Second/10))
		speaker.Play(mixer)

		select {}
	}

**Comment by faiface** [comment]
Hi, I'm sorry, I somehow completely forgot about this issue, so if it's still relevant, here's a response.

For basic usage of the library, you don't use the `Stream` method manually. `Stream` method is used to *take* new samples out of a `Streamer`, just like a `Read` method is used to take bytes out of an `io.Reader`. You only use the `Stream` method when manually implementing new kinds of streamers.

Now, regarding your use-case. When you wrap a streamer inside a `Volume` thing, you need to play the volume thing through the speakers in order to get the effect.

So, here's what you can do:
1. You load two streamers from MP3 files.
2. You wrap one of them in a `Volume` thing, thus getting a new streamer.
3. You play both of them (the MP3 file and the `Volume` wrapped thing) through the speaker.
