### ISSUE TITLE
Make Resampler's internal streamer public

### ISSUE THREAD

**Issue by skuzzymiglet** [faiface/beep#90]
I think Resampler's `s` should be public. For example, in `speaker.Play`, you can't play resampled audio. The same is true for most methods

**Comment by faiface** [comment]
Hey, you can play resampled audio. `beep.Resample` returns a `beep.Streamer` and what does `speaker.Play` accept? Of course, a `beep.Streamer`.

**Comment by skuzzymiglet** [comment]
In the GoDoc at least (https://godoc.org/github.com/faiface/beep#Resample) it returns a Resampler

**Comment by faiface** [comment]
That's right, but the `*Resampler` type implements the [`beep.Streamer`](https://godoc.org/github.com/faiface/beep#Streamer) interface because it has both the [`Stream`](https://godoc.org/github.com/faiface/beep#Resampler.Stream) and the [`Err`](https://godoc.org/github.com/faiface/beep#Resampler.Err) method required by the `Streamer` interface.

That's why you can pass a `*Resampler` wherever a `Streamer` is required.

Why return a `*Resampler` and not just a `Streamer`? That's because `*Resampler` has some more methods, like [`SetRatio`](https://godoc.org/github.com/faiface/beep#Resampler.SetRatio), which make it possible to change the resampling ratio in real-time during the playback.

**Comment by faiface** [comment]
Btw, [this part of the tutorial](https://github.com/faiface/beep/wiki/Composing-and-controlling) explains all of this quite well.

**Comment by skuzzymiglet** [comment]
If so, why am I getting this:

```
./main.go:68:11: cannot use toTempo(streamer, &format, *tempo) (type beep.Resampler) as type beep.Streamer in assignment:
        beep.Resampler does not implement beep.Streamer (Err method has pointer receiver)
```

**Comment by faiface** [comment]
Okay, I understand your issue now.

That’s because the `*beep.Resampler` implements the `beep.Streamer` interface, but not `beep.Resampler` (notice the missing `*`). Why is that? The because the methods `Stream` and `Err` for the resampler are defined on a pointer receiver, not a value receiver.

What you’re doing is you’re dereferencing your resampler with `*tempo`. That converts it  from `*beep.Resampler`, which implements `beep.Streamer` to `beep.Resampler`, which does not implement the interface.

Just drop the `*` and you’re good to go.

**Comment by skuzzymiglet** [comment]
It works OK now, but I can't get it to loop (inside a ctrl)

**Comment by skuzzymiglet** [comment]
@faiface I think it's a bug. FLAC decoded files are refusing to loop
